# Generated by Django 6.0.7 on 2026-07-24 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_account_username'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='media/posts/videos')),
                ('image', models.ImageField(upload_to='media/posts/images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
            bases=('base.basemodel',),
        ),
    ]
