# Generated by Django 6.0.7 on 2026-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_repair_missing_username_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='@', max_length=10, unique=True),
        ),
    ]
