# Generated by Django 6.0.7 on 2026-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Soch turmagi nomi')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rasm URL manzili')),
                ('target_face_shapes', models.CharField(help_text='Masalan: Oval, Dumaloq, Olmos', max_length=250, verbose_name='Mos keluvchi yuz shakllari')),
                ('description', models.TextField(verbose_name='Tavsifi (Nima uchun mos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
