# Generated by Django 6.0.7 on 2026-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Soch turmagi nomi')),
                ('category', models.CharField(choices=[('classic', 'Klassik'), ('modern', 'Zamonaviy'), ('fade', 'Fade uslubi'), ('kids', 'Bolalar uchun'), ('other', 'Boshqa')], default='modern', max_length=20, verbose_name='Kategoriya')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hairstyles/', verbose_name='Rasm (Admin paneldan yuklang)')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Rasm URL manzili (ixtiyoriy)')),
                ('target_face_shapes', models.CharField(help_text='Masalan: Oval, Dumaloq, Olmos', max_length=250, verbose_name='Mos keluvchi yuz shakllari')),
                ('description', models.TextField(verbose_name='Tavsifi (Nima uchun mos va izoh)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
