# Generated by Django 6.0.7 on 2026-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hairstyles/', verbose_name='Rasm (Admin paneldan yuklang)'),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='description',
            field=models.TextField(verbose_name='Tavsifi (Nima uchun mos va izoh)'),
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Rasm URL manzili (ixtiyoriy)'),
        ),
    ]
