# Generated by Django 6.0.7 on 2026-08-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairstyle',
            options={'verbose_name': 'Soch turmagi', 'verbose_name_plural': 'Soch turmaklari (Styles)'},
        ),
    ]
