# Generated by Django 6.0.7 on 2026-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_ai', '0002_hairstyle_image_alter_hairstyle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='category',
            field=models.CharField(choices=[('classic', 'Klassik'), ('modern', 'Zamonaviy'), ('fade', 'Fade uslubi'), ('kids', 'Bolalar uchun'), ('other', 'Boshqa')], default='modern', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
